jobs:
  close-issues:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v8
      with:
        close-issue-message: Hey there @ ${{ github.event.issue.user.login }} , we
          want to express our appreciation for your initial contribution to this issue.
          However, we now mark it as closed since we haven't received any response
          from you in the past 90 days. If you're still available, we would greatly
          appreciate it if you could provide answers to any open questions and/or
          share the requested feedback/input. Thank you for your consideration, we
          hope to hear from you soon!
        close-issue-reason: not_planned
        days-before-issue-close: 90
        days-before-issue-stale: 30
        days-before-pr-close: -1
        days-before-pr-stale: -1
        only-labels: 'Status: Needs Author Input'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: 'Status: Stale'
        stale-issue-message: Hey there @ ${{ github.event.issue.user.login }} , we
          want to express our appreciation for your initial contribution to this issue.
          However, we now mark it as stale since we haven't received any response
          from you in the past 30 days. If you're still available, we would greatly
          appreciate it if you could provide answers to any open questions and/or
          share the requested feedback/input. Thank you for your consideration, we
          hope to hear from you soon!
name: Close issues due to author inactivity
on:
  repository_dispatch:
    types: trigger-ga___autoclose.yml
